/** Справочник интересов (ru / kk). slug — стабильный ключ, не меняется. */
export const interests: { slug: string; nameRu: string; nameKk: string }[] = [
  { slug: "coffee", nameRu: "Кофе", nameKk: "Кофе" },
  { slug: "books", nameRu: "Книги", nameKk: "Кітаптар" },
  { slug: "travel", nameRu: "Путешествия", nameKk: "Саяхат" },
  { slug: "music", nameRu: "Музыка", nameKk: "Музыка" },
  { slug: "cinema", nameRu: "Кино", nameKk: "Кино" },
  { slug: "theatre", nameRu: "Театр", nameKk: "Театр" },
  { slug: "concerts", nameRu: "Концерты", nameKk: "Концерттер" },
  { slug: "standup", nameRu: "Стендап", nameKk: "Стендап" },
  { slug: "sport", nameRu: "Спорт", nameKk: "Спорт" },
  { slug: "running", nameRu: "Бег", nameKk: "Жүгіру" },
  { slug: "football", nameRu: "Футбол", nameKk: "Футбол" },
  { slug: "yoga", nameRu: "Йога", nameKk: "Йога" },
  { slug: "mountains", nameRu: "Горы", nameKk: "Таулар" },
  { slug: "hiking", nameRu: "Походы", nameKk: "Жаяу саяхат" },
  { slug: "skiing", nameRu: "Горные лыжи", nameKk: "Тау шаңғысы" },
  { slug: "photo", nameRu: "Фотография", nameKk: "Фотосурет" },
  { slug: "art", nameRu: "Искусство", nameKk: "Өнер" },
  { slug: "design", nameRu: "Дизайн", nameKk: "Дизайн" },
  { slug: "fashion", nameRu: "Мода", nameKk: "Сән" },
  { slug: "dance", nameRu: "Танцы", nameKk: "Би" },
  { slug: "cooking", nameRu: "Кулинария", nameKk: "Аспаздық" },
  { slug: "it", nameRu: "IT", nameKk: "IT" },
  { slug: "startups", nameRu: "Стартапы", nameKk: "Стартаптар" },
  { slug: "languages", nameRu: "Иностранные языки", nameKk: "Шет тілдері" },
  { slug: "psychology", nameRu: "Психология", nameKk: "Психология" },
  { slug: "podcasts", nameRu: "Подкасты", nameKk: "Подкасттар" },
  { slug: "boardgames", nameRu: "Настольные игры", nameKk: "Үстел ойындары" },
  { slug: "videogames", nameRu: "Видеоигры", nameKk: "Бейнеойындар" },
  { slug: "chess", nameRu: "Шахматы", nameKk: "Шахмат" },
  { slug: "anime", nameRu: "Аниме", nameKk: "Аниме" },
  { slug: "animals", nameRu: "Животные", nameKk: "Жануарлар" },
  { slug: "dogs", nameRu: "Собаки", nameKk: "Иттер" },
  { slug: "cars", nameRu: "Автомобили", nameKk: "Көліктер" },
  { slug: "volunteering", nameRu: "Волонтёрство", nameKk: "Еріктілік" },
];
